version: "3"

services:
  api:
    build:
      context: services/api/
      dockerfile: ../../.docker/golang/Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    image: "bot_api"
    container_name: "bot_api"
    environment:
      - CHANNEL_NAME=${API_CHANNEL_NAME}
      - BOT_OAUTH_TOKEN=${API_BOT_OAUTH_TOKEN}
      - BOT_USERNAME=${API_BOT_USERNAME}
      - IRC_URL=${API_IRC_URL}
      - IRC_PORT=${API_IRC_PORT}
  postgres:
    build:
      context: .
      dockerfile: .docker/postgres/Dockerfile
    ports:
      - "${PGSQL_PORT}:${PGSQL_PORT}"
    image: ${PGSQL_NAME}
    container_name: ${PGSQL_NAME}
    environment:
      - PGDATA=${PGSQL_DATA}
      - POSTGRES_DB=${PGSQL_DBNAME}
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD}
  redis:
    build:
      context: .
      dockerfile: .docker/redis/Dockerfile
    ports:
      - "${REDIS_PORT}:6379"
    image: ${REDIS_NAME}
    container_name: ${REDIS_NAME}
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: "bot-zookeeper"
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: "bot-kafka"
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: 'commands:1:1'
    depends_on:
      - zookeeper
